import archiver from "archiver";
import fs from "node:fs";
import path from "node:path";
import type { PageSpec, WebsiteSpec } from "@/lib/types";

const ROOT = process.cwd();

function readSource(relPath: string): string {
  return fs.readFileSync(path.join(ROOT, relPath), "utf-8");
}

function slugifyPackageName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "ai-generated-site";
}

function packageJson(spec: WebsiteSpec): string {
  return JSON.stringify(
    {
      name: slugifyPackageName(spec.meta.siteName),
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "15.1.0",
        react: "18.3.1",
        "react-dom": "18.3.1",
      },
      devDependencies: {
        "@types/node": "22.10.2",
        "@types/react": "18.3.18",
        "@types/react-dom": "18.3.5",
        autoprefixer: "10.4.20",
        postcss: "8.4.49",
        tailwindcss: "3.4.17",
        typescript: "5.7.2",
      },
    },
    null,
    2
  );
}

function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2020",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: false,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        baseUrl: ".",
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

function nextConfigJs(): string {
  return [
    "/** @type {import('next').NextConfig} */",
    "const nextConfig = {",
    "  reactStrictMode: true,",
    "};",
    "",
    "module.exports = nextConfig;",
    "",
  ].join("\n");
}

function dataSiteTs(spec: WebsiteSpec): string {
  return [
    'import type { WebsiteSpec } from "@/lib/types";',
    "",
    `const site: WebsiteSpec = ${JSON.stringify(spec, null, 2)};`,
    "",
    "export default site;",
    "",
  ].join("\n");
}

function rootLayoutTsx(spec: WebsiteSpec): string {
  return [
    'import type { Metadata } from "next";',
    'import "./globals.css";',
    "",
    "export const metadata: Metadata = {",
    `  title: ${JSON.stringify(spec.meta.siteName)},`,
    `  description: ${JSON.stringify(spec.meta.tagline)},`,
    "};",
    "",
    "export default function RootLayout({ children }: { children: React.ReactNode }) {",
    "  return (",
    `    <html lang=${JSON.stringify(spec.meta.language)} dir=${JSON.stringify(spec.meta.direction)}>`,
    "      <body>{children}</body>",
    "    </html>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function pageTsx(page: PageSpec): string {
  return [
    'import type { Metadata } from "next";',
    'import SiteRenderer from "@/lib/components/SiteRenderer";',
    'import site from "@/data/site";',
    "",
    "export const metadata: Metadata = {",
    `  title: ${JSON.stringify(page.seo.title)},`,
    `  description: ${JSON.stringify(page.seo.description)},`,
    `  keywords: ${JSON.stringify(page.seo.keywords)},`,
    "  openGraph: {",
    `    title: ${JSON.stringify(page.seo.title)},`,
    `    description: ${JSON.stringify(page.seo.description)},`,
    "  },",
    "};",
    "",
    "export default function Page() {",
    `  const page = site.pages.find((p) => p.slug === ${JSON.stringify(page.slug)});`,
    "  if (!page) return null;",
    "  return <SiteRenderer spec={site} page={page} />;",
    "}",
    "",
  ].join("\n");
}

function sitemapTs(): string {
  return [
    'import type { MetadataRoute } from "next";',
    'import site from "@/data/site";',
    "",
    'const BASE = process.env.SITE_URL || "https://example.com";',
    "",
    "export default function sitemap(): MetadataRoute.Sitemap {",
    "  return site.pages.map((p) => ({",
    '    url: p.slug === "home" ? BASE : BASE + "/" + p.slug,',
    "    lastModified: new Date(),",
    "  }));",
    "}",
    "",
  ].join("\n");
}

function robotsTs(): string {
  return [
    'import type { MetadataRoute } from "next";',
    "",
    "export default function robots(): MetadataRoute.Robots {",
    '  const base = process.env.SITE_URL || "https://example.com";',
    "  return {",
    '    rules: { userAgent: "*", allow: "/" },',
    '    sitemap: base + "/sitemap.xml",',
    "  };",
    "}",
    "",
  ].join("\n");
}

function readmeMd(spec: WebsiteSpec): string {
  return [
    `# ${spec.meta.siteName}`,
    "",
    "Generated by the AI Sales Employee website builder.",
    "",
    "## Getting started",
    "",
    "```bash",
    "npm install",
    "npm run dev",
    "```",
    "",
    "Open http://localhost:3000.",
    "",
    "## Production build",
    "",
    "```bash",
    "npm run build",
    "npm start",
    "```",
    "",
    "## Notes",
    "",
    "- Set the `SITE_URL` environment variable when deploying so `/sitemap.xml` and `/robots.txt` point at your real domain.",
    '- Any section showing a soft gradient box is a placeholder waiting on a real photo. Add images under `/public` and update the matching "image"/"url" fields in `data/site.ts`.',
    "- All content lives in `data/site.ts` as one typed object — edit it directly, or regenerate it from the AI Sales Employee app.",
    "- This project has no dependency on any AI provider or database — it is a plain, static-content Next.js app.",
    "",
  ].join("\n");
}

export async function buildExportZip(spec: WebsiteSpec): Promise<Buffer> {
  const archive = archiver("zip", { zlib: { level: 9 } });
  const chunks: Buffer[] = [];
  archive.on("data", (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<void>((resolve, reject) => {
    archive.on("end", () => resolve());
    archive.on("error", reject);
  });

  const componentFiles = fs.readdirSync(path.join(ROOT, "lib/components")).filter((f) => f.endsWith(".tsx"));
  for (const file of componentFiles) {
    archive.append(readSource(`lib/components/${file}`), { name: `lib/components/${file}` });
  }
  archive.append(readSource("lib/types.ts"), { name: "lib/types.ts" });
  archive.append(readSource("app/globals.css"), { name: "app/globals.css" });
  archive.append(readSource("tailwind.config.ts"), { name: "tailwind.config.ts" });
  archive.append(readSource("postcss.config.js"), { name: "postcss.config.js" });

  archive.append(packageJson(spec), { name: "package.json" });
  archive.append(tsconfigJson(), { name: "tsconfig.json" });
  archive.append(nextConfigJs(), { name: "next.config.js" });
  archive.append(dataSiteTs(spec), { name: "data/site.ts" });
  archive.append(rootLayoutTsx(spec), { name: "app/layout.tsx" });
  archive.append(sitemapTs(), { name: "app/sitemap.ts" });
  archive.append(robotsTs(), { name: "app/robots.ts" });
  archive.append(readmeMd(spec), { name: "README.md" });
  archive.append("node_modules\n.next\n.env*\n", { name: ".gitignore" });

  for (const page of spec.pages) {
    const filePath = page.slug === "home" ? "app/page.tsx" : `app/${page.slug}/page.tsx`;
    archive.append(pageTsx(page), { name: filePath });
  }

  // Copy any uploaded assets referenced by this project so the export is self-contained.
  const uploadsDir = path.join(ROOT, "public", "uploads");
  if (fs.existsSync(uploadsDir)) {
    for (const asset of spec.assets) {
      const assetPath = path.join(ROOT, "public", asset.url.replace(/^\//, ""));
      if (fs.existsSync(assetPath)) {
        archive.append(fs.createReadStream(assetPath), { name: `public${asset.url}` });
      }
    }
  }

  await archive.finalize();
  await done;
  return Buffer.concat(chunks);
}
